name: qr_viewer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^1.6.11
  barcode_scan: ^3.0.1
  sqflite: ^1.3.1
  url_launcher: ^5.5.0
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
